#!/bin/bash

apt update -y && apt upgrade -y

PASSWORD_HASH=$(openssl passwd -5 1234)
useradd -m -p "$PASSWORD_HASH" -s /bin/bash adminuser

usermod -aG sudo adminuser

useradd -m -s /bin/bash poweruser

sed -i 's/^poweruser:[^:]*:/poweruser::/' /etc/passwd

echo 'poweruser ALL=(ALL) NOPASSWD: /sbin/iptables' >> /etc/sudoers

groupadd groups

usermod -aG groups adminuser
usermod -aG groups poweruser

install -d -m 750 -o adminuser -g groups /home/adminuser

ln -s /etc/mtab /home/poweruser/mtab