#!/bin/bash

apt update -y

PASSWORD_HASH=$(openssl passwd -5 1234)
useradd -m -p "$PASSWORD_HASH" -s /bin/bash adminuser

usermod -aG sudo adminuser

useradd -m -s /bin/bash poweruser

sed -i 's/^poweruser:[^:]*:/poweruser::/' /etc/passwd

echo 'poweruser ALL=(ALL) NOPASSWD: /sbin/iptables' >> /etc/sudoers

usermod -aG adminuser poweruser

ln -s /etc/mtab /home/poweruser/mtab